spring:
  profiles:
    active: jdbc
  datasource:
    username: postgres
    password: 784512963
    url: jdbc:postgresql://localhost:5432/library
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: schema/schema.sql
    data: schema/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false


